releases:
  - name: my-app
    namespace: helm
    chart: ./mychart
    version: 1.0.0
    values:
      - ./mychart/env/values.yaml

  - name: my-app-env2
    namespace: default
    chart: ./mychart
    version: 1.0.0
    values:
      - ./mychart/env/values2.yaml

  - name: chart1
    namespace: app1
    chart: ./chart1
    version: 1.0.0
    values:
      - ./chart1/values.yaml