replicaCount: 2

image:
  repository: nginx
  tag: "1.25"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

secretEnv:
  - name: DB_PASSWORD
    key: dbPassword
  - name: API_TOKEN
    key: apiToken
