apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ include "mychart.name" . }}
data:
  {{- range .Values.config }}
  {{ .key }}: {{ .name | quote }}
  {{- end }}