apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ include "mychart.name" . }}
    environment: {{ .Values.labels.environment }}
    team: {{ .Values.labels.team }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mychart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mychart.name" . }}
        environment: {{ .Values.labels.environment }}
        team: {{ .Values.labels.team }}
    spec:
      containers:
        - name: {{ include "mychart.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range .Values.secretEnv }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: k-secret
                  key: {{ .key | quote }}
            {{- end }}

            {{- range .Values.config }}
            - name: {{ .name }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Release.Name }}-config
                  key: {{ .key | quote }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config

